'use client'

import './globals.css'
// eslint-disable-next-line camelcase
import { Bebas_Neue } from 'next/font/google'
import { createTheme, NextUIProvider } from '@nextui-org/react'
import { colors } from '../constants/constants.js'
import { Button } from '../components/button'
import Link from 'next/link'

const bebasNeue = Bebas_Neue({
  weight: '400',
  style: ['normal'],
  subsets: ['latin']
})

const theme = createTheme({
  type: 'light', // it could be "light" or "dark"
  theme: {
    colors,
    space: {},
    fonts: {}
  }
})

// export const metadata = {
//   title: 'Datalab',
//   description: 'Generated by create next app'
// }

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={bebasNeue.className}>
        <header className='flex justify-between items-center px-8 pt-8'>
          <Link href='/'>
            <h1 className='flex flex-grow-0 text-primary text-2xl tracking-normal cursor-pointer'>Datamoroni</h1>
          </Link>
          <input className='rounded-xl border-transparent bg-gray-100 px-4 py-2 text-xl focus:border-primary outline-none border-4 focus:w-80 transition-all duration-500' placeholder='Search player' type='text' />
          <div className='flex flex-grow-0 gap-3'>
            <Button color='secondary'>
              Login
            </Button>
            <Button color='primary'>
              Get Started
            </Button>
          </div>
        </header>
        <NextUIProvider theme={theme}>
          {children}
        </NextUIProvider>
      </body>
    </html>
  )
}
